name: Publish Hugo Website to GitHub Pages

on:
  push:
    branches:
      - main # Change this to the branch you want to trigger the workflow from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"

      - name: Build
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish-dir: ./public
          github_token: ${{ secrets.GITHUB_TOKEN }}
